### ISSUE TITLE
DInput Keyboard Class

### ISSUE THREAD

**Issue by planetchili** [planetchili/Ballistiks-Mk-I#1]
Awesome work on the input stuff so far L1Fe. One suggestion though, instead of rewriting the original keyboard class, create a new class that inherits from Controller. That way we can maintain support for both DInput keyboard and for windows message keyboard.

**Comment by lifebu** [comment]
Would be good as an learning process. If anybody of the forums will see the final Game, they can explore several ways how to implement things. Good Idea. 
Shall I devide the DInputControllers into more SubController?
DInputKeyboardController, DInputMouseController, DInputGamepadController?
So we would have 4 Controllers?
For the time being, I will let this as it is. First I want to create more access functions, more features and more Settings for the DInput Class. When I'm satisfied with the way DInput works, I will create 3 new Controllers, which use Functions of DInput to operate. Just like you suggested it ^^

**Comment by lifebu** [comment]
I'll try to do the same thing later on Hardware Acceleration. Making it an own module. So you can switch between Chilis Software Renderer with DirectX Hardware Renderer, as you please (even runtime?). Maybe Later we can combine all Modules to form one DirectX Module.
Still a lot of funny things to do and to learn, but we'll get to it :D

**Comment by lifebu** [comment]
Had an Idea. Maybe I could utilize Reference Counters. When the first Type of DInputController is created, Dinput will be initialized. When this Pointer reaches 0, so no DInputControllers exist in the Engine, DInput will destruct itself.
Though this would make it difficult to switch The InputHandlerModules (Dinput or Windowsmessages or anything we implement.) in Runtime. But on the other Hand having a lot of Modules Initialized (like DInput, Direct3D, DirectSound,any of the GDI Components or any of the OpenGL Components), our Programm might be bloated extremly and Slow down the whole Game in the End.

**Comment by planetchili** [comment]
> Shall I devide the DInputControllers into more SubController?
> DInputKeyboardController, DInputMouseController, DInputGamepadController?

Yeah, I think that's a good idea. One controller for each style of control. So there would be keyboard; keyboard + mouse; and gamepad.

> For the time being, I will let this as it is. First I want to create more access functions, more features and more Settings for the DInput Class. When I'm satisfied with the way DInput works, I will create 3 new Controllers, which use Functions of DInput to operate. Just like you suggested it ^^

That sounds perfect.

> I'll try to do the same thing later on Hardware Acceleration. Making it an own module. So you can switch between Chilis Software Renderer with DirectX Hardware Renderer, as you please (even runtime?). 

I've also thought of this. It would be neat to implement, but it will be a lot more difficult than for the controllers so don't knock yourself out over it. We can always maintain separate branches for the different graphics versions and update them all independently if we want to maintain both.

> Had an Idea. Maybe I could utilize Reference Counters. When the first Type of DInputController is created, Dinput will be initialized. When this Pointer reaches 0, so no DInputControllers exist in the Engine, DInput will destruct itself.
> Though this would make it difficult to switch The InputHandlerModules (Dinput or Windowsmessages or anything we implement.) in Runtime. But on the other Hand having a lot of Modules Initialized (like DInput, Direct3D, DirectSound,any of the GDI Components or any of the OpenGL Components), our Programm might be bloated extremly and Slow down the whole Game in the End.

This isn't a bad idea, but again will be trickier to implement. The savings on efficiency probably won't be that great either, so don't kill yourself trying to get it to work or anything. Still, it would be neat from an architectural / elegance point of view. :grin:

**Comment by lifebu** [comment]
If you put the renderers or InputManager in seperet .dll's you might be able to load it easilier. Also You can use this .dll's for the other games/project. But that's an advanced topic and is a cool idea for the future. For the moment I would be completely happy if the code works as it should.
